export enum MESSAGES_EVENT_ENUM {
  START_GETTING_ELEMENT = "start-getting-element",
  END_GETTING_ELEMENT = "end-getting-element",
  CLEAN_UP = "clean-up",
  HIGHLIGHT_ELEMENT = "highlight-element",
  PREVIEW_TOUR = "preview-tour",
  SELECT_ELEMENT = "select-element",
  HANDSHAKE = "handshake",
  CONNECTION_ESTABLISHED = "connection-established",
  ON_LOADED = "on-loaded",
  SHOW_TOUR = "show-tour",
  CURRENT_STEP_INDEX = "current-step-index",
  READY_FOR_TOURING = "ready-for-touring",
  STORE_USER_ID = "store-user-id",
  CREDENTIALS_FROM_POPUP = "credentials-from-popup",
  CREDENTIALS_FROM_EDITOR = "credentials-from-editor",
  CLOSE_VIDEO_POPUP = "close-video-popup",
}
